-- Add flashcards to existing lessons
UPDATE lessons SET content = jsonb_set(
  COALESCE(content, '{}'::jsonb),
  '{flashcards}',
  '[
    {"front": "What is Python?", "back": "A high-level, interpreted programming language known for its readability and versatility."},
    {"front": "Who created Python?", "back": "Guido van Rossum, first released in 1991."},
    {"front": "Is Python compiled or interpreted?", "back": "Python is an interpreted language — code runs line by line without a separate compilation step."},
    {"front": "Name 3 popular uses of Python", "back": "Web development, data science/ML, and automation/scripting."}
  ]'::jsonb
) WHERE id = 'b1b1b1b1-b1b1-41b1-81b1-b1b1b1b1b1b1';

UPDATE lessons SET content = jsonb_set(
  COALESCE(content, '{}'::jsonb),
  '{flashcards}',
  '[
    {"front": "What is a variable in Python?", "back": "A named reference to a value stored in memory, created with the = operator."},
    {"front": "Name 4 basic data types in Python", "back": "int (integers), float (decimals), str (strings), bool (True/False)."},
    {"front": "How do you check a variable type?", "back": "Use the type() function, e.g. type(42) returns <class int>."},
    {"front": "What is the difference between int and float?", "back": "int holds whole numbers (42), float holds decimal numbers (3.14)."},
    {"front": "How do you convert a string to an integer?", "back": "Use int(), e.g. int(\"42\") returns 42."}
  ]'::jsonb
) WHERE id = 'b2b2b2b2-b2b2-41b2-81b2-b2b2b2b2b2b2';

UPDATE lessons SET content = jsonb_set(
  COALESCE(content, '{}'::jsonb),
  '{flashcards}',
  '[
    {"front": "How do you create a list in Python?", "back": "Use square brackets: my_list = [1, 2, 3]"},
    {"front": "What is a for loop?", "back": "A control structure that iterates over a sequence: for item in list:"},
    {"front": "How do you define a function?", "back": "Use the def keyword: def my_function(param):"},
    {"front": "What does the return statement do?", "back": "It exits a function and sends a value back to the caller."},
    {"front": "What is the difference between a list and a tuple?", "back": "Lists are mutable (can be changed), tuples are immutable (cannot be changed after creation)."}
  ]'::jsonb
) WHERE id = 'b3b3b3b3-b3b3-41b3-81b3-b3b3b3b3b3b3';

-- Add Module 2: Data Structures and File IO
INSERT INTO modules (id, course_id, title, description, order_index)
VALUES ('a2a2a2a2-a2a2-42a2-82a2-a2a2a2a2a2a2', 'c1c1c1c1-c1c1-41c1-81c1-c1c1c1c1c1c1', 'Data Structures and File I/O', 'Master Python built-in data structures and learn to read and write files', 1);

INSERT INTO lessons (id, module_id, title, type, duration, order_index, content) VALUES
('d1d1d1d1-d1d1-41d1-81d1-d1d1d1d1d1d1', 'a2a2a2a2-a2a2-42a2-82a2-a2a2a2a2a2a2', 'Dictionaries and Sets', 'reading', '10 min', 0,
 '{"body": "Dictionaries are one of Python''s most powerful data structures. They store key-value pairs and provide fast lookups.\n\nA dictionary is created using curly braces with key: value pairs. Keys must be immutable (strings, numbers, tuples), while values can be anything.\n\nSets are unordered collections of unique elements. They are perfect for removing duplicates and performing mathematical set operations like union, intersection, and difference.", "code_snippets": [{"title": "Working with Dictionaries", "description": "Create and manipulate dictionaries", "code": "student = {\"name\": \"Alice\", \"age\": 22, \"grade\": \"A\"}\n\nprint(student[\"name\"])\nprint(student.get(\"major\", \"Undeclared\"))\n\nstudent[\"major\"] = \"Computer Science\"\n\nfor key, value in student.items():\n    print(f\"{key}: {value}\")"}], "flashcards": [{"front": "How do you create a dictionary?", "back": "Use curly braces with key-value pairs: d = {\"key\": \"value\"}"}, {"front": "What is the time complexity of dictionary lookup?", "back": "O(1) average case — dictionaries use hash tables internally."}, {"front": "How do sets differ from lists?", "back": "Sets are unordered, contain only unique elements, and support set operations (union, intersection)."}, {"front": "What types can be dictionary keys?", "back": "Only immutable types: strings, numbers, and tuples."}]}'::jsonb),

('d2d2d2d2-d2d2-41d2-81d2-d2d2d2d2d2d2', 'a2a2a2a2-a2a2-42a2-82a2-a2a2a2a2a2a2', 'String Methods and Formatting', 'reading', '8 min', 1,
 '{"body": "Strings in Python are immutable sequences of characters with a rich set of built-in methods.\n\nString formatting lets you embed expressions inside string literals. Python 3 offers f-strings (formatted string literals), which are the most readable and preferred approach.\n\nCommon string methods include .upper(), .lower(), .strip(), .split(), .join(), .replace(), and .find().", "code_snippets": [{"title": "String Operations", "description": "Practice common string methods and f-strings", "code": "name = \"Python Programming\"\n\nprint(name.upper())\nprint(name.lower())\nprint(name.split())\n\nfirst = \"Hello\"\nlast = \"World\"\nprint(f\"{first}, {last}!\")\n\nprint(name[0:6])\nprint(name[::-1])"}], "flashcards": [{"front": "What are f-strings?", "back": "Formatted string literals (f\"...\") that let you embed expressions directly: f\"Hello {name}\""}, {"front": "Are strings mutable in Python?", "back": "No — strings are immutable. Methods like .upper() return new strings."}, {"front": "How do you split a string into a list?", "back": "Use .split(separator): \"a,b,c\".split(\",\") returns [\"a\", \"b\", \"c\"]"}]}'::jsonb),

('d3d3d3d3-d3d3-41d3-81d3-d3d3d3d3d3d3', 'a2a2a2a2-a2a2-42a2-82a2-a2a2a2a2a2a2', 'Reading and Writing Files', 'reading', '10 min', 2,
 '{"body": "File I/O is essential for real-world Python programs. Python uses the built-in open() function to work with files.\n\nThe with statement (context manager) is the recommended way to handle files — it automatically closes the file when done, even if an error occurs.\n\nCommon file modes include r (read), w (write/overwrite), a (append), and r+ (read and write).", "code_snippets": [{"title": "File Operations Demo", "description": "Writing and reading text files", "code": "# Writing to a file\nwith open(\"example.txt\", \"w\") as f:\n    f.write(\"Hello, Python!\\n\")\n    f.write(\"File I/O is easy.\\n\")\n\n# Reading from a file\nwith open(\"example.txt\", \"r\") as f:\n    content = f.read()\n    print(content)"}], "flashcards": [{"front": "Why use with open() instead of just open()?", "back": "The with statement automatically closes the file, even if an exception occurs."}, {"front": "What does file mode a do?", "back": "Append mode — writes to the end of the file without overwriting existing content."}, {"front": "How do you read a file line by line?", "back": "Use a for loop: for line in file: or call file.readlines() to get a list."}]}'::jsonb),

('d4d4d4d4-d4d4-41d4-81d4-d4d4d4d4d4d4', 'a2a2a2a2-a2a2-42a2-82a2-a2a2a2a2a2a2', 'Quiz: Data Structures', 'quiz', '5 min', 3,
 '{"questions": [{"question": "Which data structure uses key-value pairs?", "options": ["List", "Dictionary", "Tuple", "Set"], "correct": 1}, {"question": "What does the .strip() string method do?", "options": ["Splits the string", "Removes whitespace from both ends", "Converts to uppercase", "Reverses the string"], "correct": 1}, {"question": "What is the recommended way to open files in Python?", "options": ["open() alone", "try/finally block", "with statement", "os.open()"], "correct": 2}, {"question": "Which of these is mutable?", "options": ["String", "Tuple", "Integer", "List"], "correct": 3}]}'::jsonb);

-- Add Module 3: Object-Oriented Programming
INSERT INTO modules (id, course_id, title, description, order_index)
VALUES ('a3a3a3a3-a3a3-43a3-83a3-a3a3a3a3a3a3', 'c1c1c1c1-c1c1-41c1-81c1-c1c1c1c1c1c1', 'Object-Oriented Programming', 'Learn classes, objects, inheritance, and OOP design principles', 2);

INSERT INTO lessons (id, module_id, title, type, duration, order_index, content) VALUES
('e1e1e1e1-e1e1-41e1-81e1-e1e1e1e1e1e1', 'a3a3a3a3-a3a3-43a3-83a3-a3a3a3a3a3a3', 'Classes and Objects', 'reading', '12 min', 0,
 '{"body": "Object-Oriented Programming (OOP) organizes code around objects — instances of classes that bundle data (attributes) and behavior (methods).\n\nA class is a blueprint for creating objects. The __init__ method is a special constructor that initializes new objects. The self parameter refers to the instance being created.\n\nPython supports all major OOP concepts: encapsulation, inheritance, polymorphism, and abstraction.", "code_snippets": [{"title": "Creating a Class", "description": "Define a Dog class with attributes and methods", "code": "class Dog:\n    def __init__(self, name, breed):\n        self.name = name\n        self.breed = breed\n        self.tricks = []\n    \n    def learn_trick(self, trick):\n        self.tricks.append(trick)\n    \n    def show_tricks(self):\n        if self.tricks:\n            print(f\"{self.name} knows: {\", \".join(self.tricks)}\")\n        else:\n            print(f\"{self.name} has no tricks yet.\")\n\nmy_dog = Dog(\"Rex\", \"German Shepherd\")\nmy_dog.learn_trick(\"sit\")\nmy_dog.learn_trick(\"shake\")\nmy_dog.show_tricks()"}], "flashcards": [{"front": "What is a class in Python?", "back": "A blueprint for creating objects that defines attributes (data) and methods (behavior)."}, {"front": "What does __init__ do?", "back": "It is the constructor — automatically called when creating a new object to initialize its attributes."}, {"front": "What does self refer to?", "back": "The current instance of the class, allowing methods to access the objects own attributes."}, {"front": "What is encapsulation?", "back": "Bundling data and methods that operate on that data within a single class."}]}'::jsonb),

('e2e2e2e2-e2e2-41e2-81e2-e2e2e2e2e2e2', 'a3a3a3a3-a3a3-43a3-83a3-a3a3a3a3a3a3', 'Inheritance and Polymorphism', 'reading', '10 min', 1,
 '{"body": "Inheritance allows a class to inherit attributes and methods from a parent class, promoting code reuse.\n\nThe child class can override parent methods to provide specialized behavior — this is polymorphism. The super() function calls the parent methods from the child.\n\nPolymorphism means many forms — different classes can implement the same method name with different behavior.", "code_snippets": [{"title": "Inheritance Example", "description": "Create an Animal hierarchy with inheritance", "code": "class Animal:\n    def __init__(self, name):\n        self.name = name\n    \n    def speak(self):\n        return \"...\"\n\nclass Cat(Animal):\n    def speak(self):\n        return f\"{self.name} says Meow!\"\n\nclass Dog(Animal):\n    def speak(self):\n        return f\"{self.name} says Woof!\"\n\nanimals = [Cat(\"Whiskers\"), Dog(\"Buddy\"), Cat(\"Luna\")]\nfor animal in animals:\n    print(animal.speak())"}], "flashcards": [{"front": "What is inheritance?", "back": "A mechanism where a child class inherits attributes and methods from a parent class."}, {"front": "What is polymorphism?", "back": "The ability for different classes to implement the same method name with different behavior."}, {"front": "What does super() do?", "back": "Calls a method from the parent class, commonly used to extend the parent constructor."}, {"front": "Inheritance vs Composition?", "back": "Inheritance = is-a (Dog is an Animal). Composition = has-a (Car has an Engine)."}]}'::jsonb),

('e3e3e3e3-e3e3-41e3-81e3-e3e3e3e3e3e3', 'a3a3a3a3-a3a3-43a3-83a3-a3a3a3a3a3a3', 'OOP Lab: Build a Library System', 'assignment', '15 min', 2,
 '{"body": "In this lab, you will apply OOP concepts to build a simple library management system.\n\nCreate Book and Library classes that work together. The Library class will manage a collection of books, supporting operations like adding books, searching by title, and checking books in and out.", "code_snippets": [{"title": "Library System Starter", "description": "Build and extend the library system", "code": "class Book:\n    def __init__(self, title, author):\n        self.title = title\n        self.author = author\n        self.is_available = True\n    \n    def __str__(self):\n        status = \"Available\" if self.is_available else \"Checked Out\"\n        return f\"{self.title} by {self.author} [{status}]\"\n\nclass Library:\n    def __init__(self, name):\n        self.name = name\n        self.books = []\n    \n    def add_book(self, book):\n        self.books.append(book)\n        print(f\"Added: {book.title}\")\n    \n    def list_books(self):\n        print(f\"\\n{self.name} catalog:\")\n        for book in self.books:\n            print(f\"  {book}\")\n\nlib = Library(\"City Library\")\nlib.add_book(Book(\"1984\", \"George Orwell\"))\nlib.add_book(Book(\"Dune\", \"Frank Herbert\"))\nlib.list_books()"}], "flashcards": [{"front": "What is the __str__ method?", "back": "A special method that defines how an object is represented as a string, used by print() and str()."}, {"front": "When should you use a class vs a function?", "back": "Use a class when you need to bundle related data and behavior, especially with multiple instances."}]}'::jsonb),

('e4e4e4e4-e4e4-41e4-81e4-e4e4e4e4e4e4', 'a3a3a3a3-a3a3-43a3-83a3-a3a3a3a3a3a3', 'Quiz: OOP Concepts', 'quiz', '5 min', 3,
 '{"questions": [{"question": "What method is called when creating a new object?", "options": ["__new__", "__init__", "__create__", "__start__"], "correct": 1}, {"question": "What does self represent in a method?", "options": ["The class itself", "The current instance", "The parent class", "A global variable"], "correct": 1}, {"question": "What is polymorphism?", "options": ["Creating multiple classes", "Same method name, different behavior", "Hiding data", "Multiple inheritance"], "correct": 1}, {"question": "Which syntax is used for inheritance?", "options": ["class Child extends Parent", "class Child inherits Parent", "class Child(Parent):", "class Child -> Parent:"], "correct": 2}]}'::jsonb);